### PR TITLE
Standardize the removal of null and empty fields on the frontend

### LINKED ISSUE #216: Updating a Line Items's receiving group doesn't work

### PR DESCRIPTION
**Pull request by deammer**
This refactor stems from [this discussion](https://github.com/distributeaid/shipment-tracker/pull/168#discussion_r657333035). We want to remove empty/null fields before sending them to the backend. This PR adds a utility method to do just that.

This PR also resolves #216 and adds support for unit tests on the frontend through a GitHub action.

### CODE REVIEW

File: src/resolvers/line_items.ts [hunk 1]
```diff
@@ -256,22 +252,12 @@ async function getUpdateAttributes(
...
-  updateAttributes: Partial<LineItemAttributes>,
   attr: 'acceptedReceivingGroupId' | 'proposedReceivingGroupId',
 ) {
-  if (
-    !('acceptedReceivingGroupId' in input) ||
-    input[attr] === lineItem[attr]
-  ) {
-    return
-  }
-
```
Comment (deammer) [inline src/resolvers/line_items.ts:271]: I removed this because if the value stayed the same, it would get deleted in the database, which isn't what we wanted.

File: src/resolvers/line_items.ts [hunk 2]
```diff
@@ -388,38 +374,36 @@ const moveLineItem: MutationResolvers['moveLineItem'] = async (
 }
 
 // Line item custom resolvers
-const proposedReceivingGroup: LineItemResolvers['proposedReceivingGroup'] = async (
-  parent,
-) => {
-  if (!parent.proposedReceivingGroupId) {
-    return null
-  }
+const proposedReceivingGroup: LineItemResolvers['proposedReceivingGroup'] =
```
Comment (deammer) [inline src/resolvers/line_items.ts:377]: I didn't change anything in this resolver, so our code formatters are probably out of sync.

File: src/resolvers/line_items.ts (hunk 1 above)
Comment (deammer) [reply src/resolvers/line_items.ts:271]: This is the fix for #216.

File: frontend/src/utils/data.ts [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+ * Strips empty, undefined, and null fields from an object. This method is
+ * intentionally NOT recursive.
+ *
+ * @example setEmptyFieldsToUndefined({
+ *   a: "",
+ *   b: null,
+ *   c: 123
+ * })
+ * // returns { c: 123 }
+ */
```
Comment (coderbyheart) [inline frontend/src/utils/data.ts:11]: **suggestion:** turn this into a unit test. It will serve as an example AND verify that `setEmptyFieldsToUndefined` does what it's supposed to be.

**Review by coderbyheart — APPROVED** [review]

File: frontend/babel.config.js [hunk 4]
```diff
@@ -0,0 +1,6 @@
+module.exports = {
+  presets: [
+    ['@babel/preset-env', { targets: { node: 'current' } }],
+    '@babel/preset-typescript',
+  ],
+}
```
Comment (deammer) [inline frontend/babel.config.js:6]: Jest requires Babel to parse TypeScript code.

File: frontend/src/utils/data.ts (hunk 3 above)
Comment (deammer) [reply frontend/src/utils/data.ts:11]: Good idea, and done.
