### PR TITLE
Delete line items when deleting a pallet

### LINKED ISSUE #272: deleting a pallet doesn't work if it has line items. We should show a confirmation dialog and then handle the deletions properly.

### PR DESCRIPTION
**Pull request by deammer**
Resolves #272.

Cascade the deletion of pallets to their associated line items. We should implement soft-deletion in the future, but not for v1.

### CODE REVIEW

File: src/models/line_item.ts [hunk 1]
```diff
@@ -68,7 +68,10 @@ export default class LineItem extends Model<
   @Column
   public offerPalletId!: number
 
-  @BelongsTo(() => Pallet, 'offerPalletId')
+  @BelongsTo(() => Pallet, {
+    foreignKey: 'offerPalletId',
+    onDelete: 'CASCADE',
```
Comment (coderbyheart) [inline src/models/line_item.ts:73]: @deammer this is all you need. It lets the database take care of deleting all entries that reference the pallet via a foreign key, when the pallet is deleted.

File: src/tests/pallets_api.test.ts [hunk 2]
```diff
@@ -298,6 +312,8 @@ describe('Pallets API', () => {
       expect(res.errors).toBeUndefined()
       expect(await Pallet.findByPk(palletA.id)).toBeNull()
       expect(res.data?.destroyPallet?.pallets?.[0].id).toEqual(palletB.id)
+
+      expect(await LineItem.findByPk(lineItem.id)).toBeNull()
```
Comment (coderbyheart) [inline src/tests/pallets_api.test.ts:316]: **praise:** nice test!

**Review by coderbyheart — APPROVED** [review]

File: src/models/line_item.ts (hunk 1 above)
Comment (deammer) [reply src/models/line_item.ts:73]: That's amazing 🤯 thank you!
